language: python
python:
    - "3.6"

# command to install dependencies
install:
    - "pip install -r requirements.txt"

# commands to run tests
before_script:
    - pg_isready

script:
    - nosetests

after_success:
    - codecov

services:
    - postgresql
