language: python
python:
  - "3.6"

# command to install dependencies
install: "pip install -r requirements.txt"

services:
  - postgresql
 
env:
  - DATABASE_URI = os.getenv("DATABASE_URI", "postgres://postgres:postgres@localhost:5432/postgres")

# commands to run tests
before_script: 
  - psql -c 'create database postgres;' -U postgres

script:
  - nosetests

after_success:
  - codecov
